tasks:
  - init: cd .. && git clone https://github.com/gabime/spdlog && cd spdlog && mkdir build && cd build && cmake .. && sudo make -j install && cd .. && mkdir build && cd build && cmake -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo ../dtq && ninja install
image:
  file: .gitpod.Dockerfile
